### ISSUE TITLE
Bug: Hint text not visible

### ISSUE THREAD

**Issue by princeraj-pr** [PratyushSingh07/BumbleCardSwipe#13]
In some devices, the hint text at the bottom is either not visible or only partially visible.

![Screenshot_2023-12-17-15-30-32-11_6378d0b0aa0dce502ca8dfc42f89f329](https://github.com/PratyushSingh07/BumbleCardSwipe/assets/40030547/3deb944d-ef8b-4e4d-86ed-8c2081b7fdfb)

![Screenshot_2023-12-17-15-29-52-85_6378d0b0aa0dce502ca8dfc42f89f329](https://github.com/PratyushSingh07/BumbleCardSwipe/assets/40030547/f9a33bdf-72c5-4a8b-8086-eb3cee2413d8)

Device info for not visible:
Phone: Realme 6
Android version: 11

Device info for partially visible:
Phone: Realme X
Android version: 11

**Comment by princeraj-pr** [comment]
Hello @PratyushSingh07, Please review this issue and assign it to me.

**Comment by PratyushSingh07** [comment]
Sure you can work on it
