### ISSUE TITLE
Design: Add a visually appealing background to all the profile card

### ISSUE THREAD

**Issue by princeraj-pr** [PratyushSingh07/BumbleCardSwipe#16]
We can add card backgrounds from this site
https://app.haikei.app/

Sample:
![Screenshot 2023-12-17 191907](https://github.com/PratyushSingh07/BumbleCardSwipe/assets/40030547/67784011-dedd-4ee9-9626-b3638842873a)
![Screenshot 2023-12-17 191856](https://github.com/PratyushSingh07/BumbleCardSwipe/assets/40030547/d1cf5ab3-13e0-4e2b-92a6-7c18b7038daf)

**Comment by PratyushSingh07** [comment]
hey @princeraj-pr , this is actually a library so I dont think making it visually vibrant would make a lot of difference. So i will have to close this issue
